### ISSUE TITLE
openPMD adios2 output missing

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#3382]
I just ran a default LWFA simulation on summit using ADIOS2 (adios2/2.5.0 module) and openPMD-api 0.12.0. PIConGPU compiled without problems and the interface for the openPMD plugin was created. However, no ~~`*.bp`~~ output files are created. The openPMD directory is completely empty. I ran both:
```
 --openPMD.period 5000:10000:2500 --openPMD.file simData --openPMD.ext bp       

 --openPMD.period 5000:10000:2500 --openPMD.file simData --openPMD.ext bp --openPMD.json '{ "adios2": { "engine": { "type": "file", "parameters": { "BufferGrowthFactor": "1.2", "InitialBufferSize": "2GB" } } } }' 
```

The openPMD directory is created and the simulation reaches 100%, but no output is created. 
stdout and stderr give no clue of an error. 

@ax3l @psychocoderHPC @franzpoeschel Any ideas what might cause this problem?

**Comment by ax3l** [comment]
ADIOS2 does not create or need `.bp` meta files anymore. You can operate completely on the directory it creates, even without a call on `bpmeta`.

This is identical to ADIOS1 behavior with `nometa` - here you just had to run `bpmeta` before you could read the data again.

**Comment by PrometheusPi** [comment]
@ax3l Sorry for the confusion: no data at all is created. (I will correct the post above.)

**Comment by ax3l** [comment]
@PrometheusPi ok, I'll let @franzpoeschel investigate this, since it seems PIConGPU specific.

Also double-check that all backends you expect in openPMD-api, esp. the ADIOS2 backend, are available, please: https://openpmd-api.readthedocs.io/en/0.12.0-alpha/citation.html#dependent-software

**Comment by franzpoeschel** [comment]
> using ADIOS2 (adios2/2.5.0 module) and openPMD-api 0.12.0

openPMD 0.12.0 requires ADIOS 2.6. Can you verify whether your openPMD build includes an ADIOS backend?

**Comment by PrometheusPi** [comment]
Okay - adios 2 2.5.5 works with openPMD-api 0.11.1 - I installed it but now I get the following compile error:
```
/.../picongpu/include/pmacc/../picongpu/plugins/openPMD/openPMDWriter.def(113): error #135: namespace "openPMD" has no member "Access"
```

**Comment by PrometheusPi** [comment]
I will remove 1fb4d57607e5192e2734883ab47b3c5f961ba094 and try again

**Comment by PrometheusPi** [comment]
Next error: 
```
/.../picongpu/include/pmacc/../picongpu/plugins/openPMD/openPMDWriter.hpp(142): error #289: no instance of constructor "openPMD::Series::Series" matches the argument list
            argument types are: (std::__cxx11::string, openPMD::AccessType, MPI_Comm, std::__cxx11::string)
```

**Comment by benjha** [comment]
I think @ax3l  prepared the latest OpenPMD software stack for Summit. This can be activated by

```
module load ums
module load ums-aph114
module load openpmd-api/0.12.0
```

**Comment by franzpoeschel** [comment]
Yeah, the openPMD plugin in PIConGPU has always relied on 0.12.0 features in the openPMD API, so your best bet is going to be installing ADIOS2.6.0 manually for now. I'm using something like this atm:
```bash
# set PREFIX to your preferred install prefix
install_adios2() {
    if [ ! -d ADIOS2 ]; then
        git clone https://github.com/ornladios/ADIOS2
    fi
    cd ADIOS2
    git checkout master
    if [ ! -d build ]; then
        mkdir build
        cd build
        cmake .. -DADIOS2_BUILD_EXAMPLES=OFF -DADIOS2_BUILD_TESTING=OFF \
            -DCMAKE_INSTALL_PREFIX="$PREFIX" -DADIOS2_USE_Fortran=OFF \
            -DADIOS2_USE_BZip2=OFF -DADIOS2_USE_PNG=OFF \
            || wait 1 && cmake .
    else
        cd build
    fi
    make -j `nproc` install
    cd ../..
}
```

**Comment by PrometheusPi** [comment]
The module provided by @ax3l worked like a charm. ADIOS2 data could be produced on summit using the openPMD plugin.

**Comment by ax3l** [comment]
Excellent, glad this helps.
Just be aware this it built against the `gcc/6.4.0` stack if you should update yours at some point.
aph114 is our ECP project for WarpX, this is the software stack: https://warpx.readthedocs.io/en/latest/building/summit.html

I requested ADIOS2 2.6.0 deployment on Summit and also triggered workflows to get newer ADIOS2 releases faster, but they seem to be still in the pipeline.

> We might want to consider throwing an exception in that case just like ADIOS1 does instead of silently doing nothing…

In order to avoid some confusion and focus maintainance, I discussed with @franzpoeschel today that we will disable ADIOS1 writes through openPMD-api in PIConGPU.
We will keep the ADIOS1 plugin in PIConGPU for a while, but we will not focus efforts on writing through openPMD-api via ADIOS1, since this diverts efforts we can put in:
- maintaining the ADIOS1 plugin, which has a stable and battle-proven implementation
- getting ADIOS2 to the same level of performance and battle-proven features

**Comment by sbastrakov** [comment]
@ax3l FYI PIConGPU already does not have HDF5 output plugin (#3361) and plan to remove all HDF5 / libSplash in other plugins two weeks (#3357). I don't think it causes conflicts with anything you wrote regarding ADIOS or openPMD-API side, just the HDF5 removal part is partialy happened already and partially will happen real soon hopefully.

**Comment by ax3l** [comment]
Thx for the heads-up @sbastrakov. Looks good.
