### ISSUE TITLE
base operand of ‘->’ is not a pointer

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3429]
Hello,

Due to the long initialization time problem, I needed to revert to ```version 0.4.3``` on one of my computers. There is ```CUDA 10.2``` installed on the system there and there is ```gcc7.5.0```. This combination works for ```@develop``` and ``` version 0.5.0``` but I had to release the upper ```CUDA``` version in order to install ```version 0.4.3``` like ```depends_on('cuda@8.0:', when='@:0.4.3 backend=cuda')``` so I deliberately went with an untested ```CUDA``` version; tested was up to ```10.1``` but not ```10.2```. Installation went fine but compilation of the typical LWFA model, out of the box, gave me an error like the one shown below. Please let me know if you see is an easy fix to this error, otherwise I would need to downgrade ```CUDA``` or ```gcc```. On the other computer ```version 0.4.3``` works with ```gcc7.4.0``` and ```CUDA 9.2``` so I am pretty sure this is due to CUDA being too new. Thank you. 
Cristian 

```
/home/cristian/src/spack/opt/spack/linux-linuxmint19-westmere/gcc-7.5.0/picongpu-0.4.3-67tzkmekenkvighsx3nm2veoacakrcmx/thirdParty/alpaka/include/alpaka/vec/Vec.hpp(924): warning: calling a __host__ function("std::__shared_count<( ::__gnu_cxx::_Lock_policy)2> ::__shared_count") from a __host__ __device__ function("alpaka::dev::DevCpu::DevCpu") is not allowed

/home/cristian/src/spack/opt/spack/linux-linuxmint19-westmere/gcc-7.5.0/picongpu-0.4.3-67tzkmekenkvighsx3nm2veoacakrcmx/thirdParty/alpaka/include/alpaka/vec/Vec.hpp(924): warning: calling a __host__ function("std::__shared_count<( ::__gnu_cxx::_Lock_policy)2> ::__shared_count") from a __host__ __device__ function("alpaka::dev::DevCpu::DevCpu [subobject]") is not allowed

/home/cristian/src/spack/opt/spack/linux-linuxmint19-westmere/gcc-7.5.0/picongpu-0.4.3-67tzkmekenkvighsx3nm2veoacakrcmx/thirdParty/alpaka/include/alpaka/core/ConcurrentExecPool.hpp: In destructor ‘alpaka::core::detail::ConcurrentExecPool<TIdx, TConcurrentExec, TPromise, TYield, TMutex, TCondVar, TisYielding>::~ConcurrentExecPool()’:
/home/cristian/src/spack/opt/spack/linux-linuxmint19-westmere/gcc-7.5.0/picongpu-0.4.3-67tzkmekenkvighsx3nm2veoacakrcmx/thirdParty/alpaka/include/alpaka/core/ConcurrentExecPool.hpp:361:19: error: base operand of ‘->’ is not a pointer
                         currentTaskPackage->setException(std::make_exception_ptr(except));
```

**Comment by sbastrakov** [comment]
Hello @cbontoiu . I do not remember details now, but at some point there was a fix in that function to enable more recent CUDA versions. 

I think the easiest is indeed to install an earlier CUDA version. Alternatively, you can try to manually implement changes from this alpaka PR https://github.com/alpaka-group/alpaka/pull/780/files however I would not advise this as there are likely other isseus popping up and it would be hard to keep track of everything.
