### ISSUE TITLE
Cannot get momentum

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#4650]
I have a model for which none of ```ux```, ```uy```,```uz``` can be retrieved from the _.bp_ data. The remaining variables,  ```x```, ```y```,```z``` and ```w``` can be obtained. I used _openpmd_ _viewer_ to read data from the _.bp_ archives. There is nothing wrong with my installation because it can get ```ux```, ```uy```,```uz``` from data saved a few months ago, so therefore with an older _dev_ release of _PIConGPU_. Something happened in between. 

In my ```speciesDefinition.param``` file I always have
```using DefaultParticleAttributes = MakeSeq_t< position<position_pic>, momentum, weighting, particleId >;```

This is the error I get:
```
uz = ts_particles.get_particle( var_list=['uz'], iteration=ITER[nnRef], species='e', plot=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[37], line 1
----> 1 uz = ts_particles.get_particle( var_list=['uz'], iteration=ITER[nnRef], species='e', plot=True)

File ~/anaconda3/lib/python3.10/site-packages/openpmd_viewer/openpmd_timeseries/main.py:274, in OpenPMDTimeSeries.get_particle(self, var_list, species, t, iteration, select, plot, nbins, plot_range, use_field_mesh, histogram_deposition, **kw)
    272 data_list = []
    273 for quantity in var_list:
--> 274     data_list.append( self.data_reader.read_species_data(
    275         iteration, species, quantity, self.extensions))
    276 # Apply selection if needed
    277 if isinstance( select, dict ):

File ~/anaconda3/lib/python3.10/site-packages/openpmd_viewer/openpmd_timeseries/data_reader/data_reader.py:293, in DataReader.read_species_data(self, iteration, species, record_comp, extensions)
    290     return h5py_reader.read_species_data(
    291             filename, iteration, species, record_comp, extensions )
    292 elif self.backend == 'openpmd-api':
--> 293     return io_reader.read_species_data(
    294             self.series, iteration, species, record_comp, extensions )

File ~/anaconda3/lib/python3.10/site-packages/openpmd_viewer/openpmd_timeseries/data_reader/io_reader/particle_reader.py:83, in read_species_data(series, iteration, species_name, component_name, extensions)
     81     if (macro_weighted == 1) and (weighting_power != 0):
     82         w_component = next(species['weighting'].items())[1]
---> 83         w = get_data( w_component )
     84         data *= w ** (-weighting_power)
     86 # - Return positions, with an offset

TypeError: get_data() missing 1 required positional argument: 'record_component'
```
Here is a snapshot from my data series as a _.bp_ archive
https://drive.google.com/file/d/1Acf8bKL_RQJOvyhViyup6fdKsFCsPih8/view?usp=drive_link

Hopefully, this is an easy fix.
Many thanks, for your help.

**Comment by pordyna** [comment]
Probably introduced with #4636 since this part of the code was not executed in the reader for `PIConGPU` output from before that PR. At first glance,  it looks like it is a bug in the `openpmd-viewer`.  Maybe try opening an issue over there and link this one.

**Comment by cbontoiu** [comment]
@pordyna thanks for your reply. I will log an issue for _openpmd-viewer_, of course. However _openpmd-viewer_ works with old PIConGPU data. Does it mean that the latest _PIConGPU_ release changed something which  _openpmd-viewer_ cannot handle, just for momentum components?

**Comment by cbontoiu** [comment]
https://github.com/openPMD/openPMD-viewer/issues/391

**Comment by pordyna** [comment]
@cbontoiu the PR mentioned above added information in the metadata that the output uses the PIC extension to the openPMD stadard. The part of the code in the viewer that fails is only executed for data with this extension. That code is supposed to automatically take care of dividing the momentum by weighting to get single particle momenta. So take care, when you get it to work, you shouldn't divide it yourself anymore.

**Comment by PrometheusPi** [comment]
This issue was investigated in https://github.com/ComputationalRadiationPhysics/picongpu/issues/4633, reported in https://github.com/ComputationalRadiationPhysics/picongpu/issues/4635 and fixed with https://github.com/ComputationalRadiationPhysics/picongpu/issues/4635. 
Please see also the comment on how to fix your PIConGPU version and how to fix your adios files here: https://github.com/openPMD/openPMD-viewer/issues/391

Since this is a fixed bug, I will close the issue. Feel free to reopen, in case I misinterpreted the issue.

**Comment by PrometheusPi** [comment]
The error was caused by an error in the openPMD-viewer: https://github.com/openPMD/openPMD-viewer/pull/393
