### ISSUE TITLE
Boost::System 1.65.1, CUDA 8.0.61

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2388]
Compiling PIConGPU with
- CUDA 8.0(.61)
- Boost 1.65.1
- GCC 5.4.0

in the latest `dev` as of 6146de12610d5c984f59b17c0792509686716b65 (already contains `--expt-relaxed-constexpr`) fails with:

```
include/boost/system/error_code.hpp(247): error: exception specification for virtual function "boost::system::error_category::std_category::equivalent(const std::error_code &, int) const" is incompatible with that of overridden function "std::_V2::error_category::equivalent(const std::error_code &, int) const"

include/boost/system/error_code.hpp(245): error: exception specification for virtual function "boost::system::error_category::std_category::equivalent(int, const std::error_condition &) const" is incompatible with that of overridden function "std::_V2::error_category::equivalent(int, const std::error_condition &) const"

include/boost/system/error_code.hpp(243): error: exception specification for virtual function "boost::system::error_category::std_category::default_error_condition" is incompatible with that of overridden function "std::_V2::error_category::default_error_condition"

include/boost/system/error_code.hpp(233): error: exception specification for virtual function "boost::system::error_category::std_category::name" is incompatible with that of overridden function "std::_V2::error_category::name"
```

**Comment by ax3l** [comment]
As this is seeing this issue still and even if we add `BOOST_NO_CXX11_NOEXCEPT` manually for all boost releases it does not vanish: looks more like a NVCC 8 issue with noexcept on virtual functions and the mismatch between the GCC 5 stdlib signature and the boost signature.

Could be possible that for nvcc 8.0 we need to rely on gcc 4.9 ...

**Comment by BenjaminW3** [comment]
alpaka does not work with NVCC 8.0 and gcc 5.0 as well. Some tests fail with:
```
/usr/include/c++/5/cmath(362): error: calling a __host__ function("__builtin_logl") from a __device__ function("std::log") is not allowed
```
or
```
/usr/include/c++/5/tuple(484) (col. 17): error: calling a __host__ function("std::_Tuple_impl<(unsigned long)0ul,  :: > ::_Tuple_impl [subobject]") from a __device__ function("std::tuple< :: > ::tuple") is not allowed
```

**Comment by ax3l** [comment]
Ok, but the C++11 tuple issue with NVCC 8 & GCC 5 is another issue that is seen on many places.

- https://stackoverflow.com/questions/40742242/does-cuda-c-not-have-tuples-in-device-code
- https://github.com/kokkos/kokkos/issues/1306
