### ISSUE TITLE
Intel/icc 12.1 Errors

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#76]
icc 12.1 on taurus (`module load intel/12.1 boost/1.54.0-intel12.1`) fails since #42 was merged in eef746a6a388552ef26ce8596f416d29fa94dbae

```
[ 16%] Building NVCC (Device) object build_picongpu/CMakeFiles/picongpu.dir//./picongpu_generated_main.cu.o
/sw/taurus/libraries/boost/1.54.0-intel12.1/include/boost/mpl/vector/aux_/preprocessed/plain/vector10.hpp(153): error: class "boost::mpl::vector<PMacc::lam
bda::placeholder<0>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_
::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>" has no member "item2"
          detected during:
            instantiation of class "boost::mpl::v_at<V, 2L> [with V=boost::mpl::vector<PMacc::lambda::placeholder<0>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>]" 
/sw/taurus/libraries/boost/1.54.0-intel12.1/include/boost/mpl/vector/aux_/at.hpp(69): here
            instantiation of class "boost::mpl::at_impl<boost::mpl::aux::vector_tag<n_>>::apply<Vector, N> [with n_=1L, Vector=boost::mpl::vector<PMacc::lambda::placeholder<0>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, N=mpl_::long_<2L>]" 
/sw/taurus/libraries/boost/1.54.0-intel12.1/include/boost/mpl/at.hpp(43): here
            instantiation of class "boost::mpl::at_c<Sequence, N> [with Sequence=boost::mpl::vector<PMacc::lambda::placeholder<0>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, N=2L]" 
/home/s4343183/src/picongpu/src/libPMacc/include/lambda/Expression.hpp(121): here
            instantiation of class "PMacc::lambda::Expression<_ExprType, _Childs> [with _ExprType=PMacc::lambda::exprTypes::terminal, _Childs=boost::mpl::vector<PMacc::lambda::placeholder<0>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>]" 
/home/s4343183/src/picongpu/src/libPMacc/include/lambda/Expression.hpp(215): here
...
```
