### PR TITLE
fix CI

### PR DESCRIPTION
**Pull request by psychocoderHPC**
bug introduced with #5370

ci: full-compile

```
/builds/hzdr/crp/picongpu/include/picongpu/../picongpu/particles/densityProfiles/GaussianImpl.hpp:50:40: error: comparison of integer expressions of different signedness: 'const pmacc::math::Vector<int, 3, pmacc::math::ArrayStorage<int, 3> >::type' {aka 'const int'} and 'const uint32_t' {aka 'const unsigned int'} [-Werror=sign-compare]
   50 |                 if(totalCellOffset.y() < ParamClass::vacuumCellsY)
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
```

### CODE REVIEW

**Review by chillenzer — APPROVED** [review]
Thanks for fixing!

**Comment by chillenzer** [comment]
Technically, to be most generic, one might want to use something like [make_unsigned](https://en.cppreference.com/w/cpp/types/make_unsigned).

**Comment by psychocoderHPC** [comment]
ping @chillenzer
