### ISSUE TITLE
Max CUDA and GCC versions for PIConGPU 0.6

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu#5348]
Do older PIConGPU releases like 0.6.0 work with newer CUDA and GCC versions? What is the upper limit?

For instance, does PIConGPU 0.6.0 work with CUDA 12.0 and gcc/g++ 11.5? Also, does adios2 2.7.1 work or is 2.7.0 the upper limit?

I am asking specifically about this version because it is the last one that still supports the Bremsstrahlung plugin so we still use it sometimes.

**Comment by psychocoderHPC** [comment]
We tested in the CI the release 0.6.0 with CUDA up to 11.2 https://github.com/ComputationalRadiationPhysics/picongpu/blob/59e9b53605f9a5c1bf271eeb055bc74370a99052/share/ci/n_wise_generator.py#L198-L201

If PIConGPU 0.6 works with CUDA 12.0 is not clear, it was not released at the time of the software release. With a modern CMake there is a high chance that it works.

The CI used for testing in the past at the point of the release ADIOS 2.7.1 for testing https://github.com/ComputationalRadiationPhysics/picongpu/blob/59e9b53605f9a5c1bf271eeb055bc74370a99052/share/ci/bash.profile#L20

**Comment by berceanu** [comment]
For future reference, Ubuntu 24+ with kernel 6.8+ has headers that are  incompatible with CUDA < 11.8, resulting in compilation errors of this type:

```
/usr/include/linux/types.h:XX:XX: error: expected initializer before ‘__s128’
```

However, it seems PIConGPU 0.6.0 does compile successfully with CUDA 11.8 and GCC 10.5 on Ubuntu 24.04.
