### PR TITLE
fix mpiexec.tpl

### LINKED ISSUE #3388: Compilation errors
Hello,

I had a fresh install of ```picongpu@develop``` with gcc version 9.3.0, ```CUDA 11.1``` and ```openmpi 4.0.5``` and there are some compilation errors for my model when using PIConGPU as ```spack load picongpu +adios %gcc@9.3.0 && export PIC_BACKEND="cuda:75"```. 

The first error was:
```include/picongpu/param/particle.param:9:10: fatal error: pmacc/nvidia/rng/distributions/Uniform_float.hpp: No such file or directory``` so I disabled the header in ```particle.para``` since I don't seem to make use of it but the second error came as ```spack/linux-linuxmint20-westmere/gcc-9.3.0/picongpu-develop-xihuo4szr2tdyxw5p5gx6scr7n3omjtp/include/pmacc/../pmacc/nvidia/atomic.hpp(95): error #304: no instance of function template "alpaka::warp::activemask" matches the argument list```. I attach to whole model as a folder where you can find the ```out.txt``` and ```out_2.txt``` compilation log files. 

I also tried using the stable PIConGPU version but there were some ```gcc``` compiler incompatibilities and I switched to ```picongpu@develop```

Maybe you can help me to debug this model, please
Thank you.
Cristian

[LAYERS-2D-PLATES.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/5385630/LAYERS-2D-PLATES.zip)

### PR DESCRIPTION
**Pull request by psychocoderHPC**
fix missing `"` introduced with #3327

fix #3388 (https://github.com/ComputationalRadiationPhysics/picongpu/issues/3388#issuecomment-714744204)

### CODE REVIEW

**Comment by steindev** [comment]
@psychocoderHPC Did you check that this is the only file where this error occurs?

**Review by steindev — APPROVED** [review]
