### ISSUE TITLE
cuda 7.5 compile broken

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1290]
Currently PIConGPU does not compile with `cuda 7.5`

**Error:**
```
.../fields/MaxwellSolver/None/NoSolver.hpp:51:76: error: ‘picongpu::SPEED_OF_LIGHT’ cannot appear in a constant-expression
.../fields/MaxwellSolver/None/NoSolver.hpp:51:93: error: ‘picongpu::SPEED_OF_LIGHT’ cannot appear in a constant-expression
.../fields/MaxwellSolver/None/NoSolver.hpp:51:111: error: ‘picongpu::DELTA_T’ cannot appear in a constant-expression
.../fields/MaxwellSolver/None/NoSolver.hpp:51:122: error: ‘picongpu::DELTA_T’ cannot appear in a constant-expression
.../fields/MaxwellSolver/None/NoSolver.hpp:51:133: error: ‘picongpu::INV_CELL2_SUM’ cannot appear in a constant-expression
.../fields/MaxwellSolver/Yee/YeeSolver.hpp: In member function ‘void picongpu::yeeSolver::YeeSolver<CurlE, CurlB>::updateE()’:
.../fields/MaxwellSolver/Yee/YeeSolver.hpp:68:76: error: ‘picongpu::SPEED_OF_LIGHT’ cannot appear in a constant-expression
.../fields/MaxwellSolver/Yee/YeeSolver.hpp:68:93: error: ‘picongpu::SPEED_OF_LIGHT’ cannot appear in a constant-expression
.../fields/MaxwellSolver/Yee/YeeSolver.hpp:68:111: error: ‘picongpu::DELTA_T’ cannot appear in a constant-expression
.../fields/MaxwellSolver/Yee/YeeSolver.hpp:68:122: error: ‘picongpu::DELTA_T’ cannot appear in a constant-expression
.../fields/MaxwellSolver/Yee/YeeSolver.hpp:68:133: error: ‘picongpu::INV_CELL2_SUM’ cannot appear in a constant-expression
.../fields/MaxwellSolver/DirSplitting/DirSplitting.hpp: At global scope:
.../fields/MaxwellSolver/DirSplitting/DirSplitting.hpp:62:77: error: ‘picongpu::SI::SPEED_OF_LIGHT_SI’ cannot appear in a constant-expression
.../fields/MaxwellSolver/DirSplitting/DirSplitting.hpp:62:101: error: ‘picongpu::SI::DELTA_T_SI’ cannot appear in a constant-expression
.../fields/MaxwellSolver/DirSplitting/DirSplitting.hpp:62:120: error: ‘picongpu::SI::CELL_WIDTH_SI’ cannot appear in a constant-expression
.../fields/MaxwellSolver/DirSplitting/DirSplitting.hpp:64:76: error: ‘picongpu::SI::CELL_HEIGHT_SI’ cannot appear in a constant-expression
.../fields/MaxwellSolver/DirSplitting/DirSplitting.hpp:64:98: error: ‘picongpu::SI::CELL_WIDTH_SI’ cannot appear in a constant-expression
.../fields/MaxwellSolver/DirSplitting/DirSplitting.hpp:67:76: error: ‘picongpu::SI::CELL_DEPTH_SI’ cannot appear in a constant-expression
.../fields/MaxwellSolver/DirSplitting/DirSplitting.hpp:67:97: error: ‘picongpu::SI::CELL_WIDTH_SI’ cannot appear in a constant-expression
```

**Comment by psychocoderHPC** [comment]
If CUDA 7.5 with enabled `C++11` is used everything compiles without errors.
**Not tested if the compiled code is valid.** (we had no  system with cuda 7.5 available)

**Comment by ax3l** [comment]
We can solve this by just using `PMACC_STATIC_ASSERT_MSG` instead. I will work on a patch today.

**Comment by ax3l** [comment]
ah no, does not solve it.

**Comment by ax3l** [comment]
Actually that is a good sign since our static assert is based on a weird behaviour of previous nvcc versions. A clean
```c++
const float a = 5.0;
BOOST_STATIC_ASSERT_MSG( a < 1.0, "this_is_an_assert" );
```
was never allowed in plain gcc host versions, either.

If we don't find a work-around, we can still do
- PIConGPU `0.2.0`: C++98 & C++11 support for CUDA 5.0-7.0 (last C++98 release)
- later releases: C++11 with CUDA 7.0+ and gcc 4.8+

Or am I missing something?

**Comment by psychocoderHPC** [comment]
Our static assert is only a wrapper for boost mpl static assert not BOOST_STATIC_ASSERT_MSG as I know both are different.

I also think about a c++98 release for cuda <=7.0.
Maybe we can add a auto switch to C++11 for cuda 7.5 in our next release.

**Comment by psychocoderHPC** [comment]
The mini example compiles with cuda 7.0 and cuda 7.5 without problems.
The examples **not** compiles with gcc/4.9.2.

**Comment by ax3l** [comment]
```bash
nvcc --keep --source-in-ptx -arch sm_20 main.cu
```
-> `main.cu.cpp.ii`
```c++
# 8 "main.cu"
const float a = ((0.5));
# 9 "main.cu"
typedef boost::static_assert_test< 1> boost_static_assert_typedef_9 __attribute((unused));
# 11 "main.cu"
struct this_is_an_assert; typedef struct this_is_an_assert11 : public mpl_::assert_
  { static mpl_::failed ************(this_is_an_assert::************assert_arg())(int) { return 0; } }
  mpl_assert_arg11; enum { mpl_assertion_in_line_11 = 4};
```

**Comment by ax3l** [comment]
One wish: can we add an advanced option to disable static asserts? This would be a nice and dirty hack to disable the error without switching to C++11 on CUDA 7.5+

**Comment by psychocoderHPC** [comment]
If [this macro](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/libPMacc/include/static_assert.hpp#L49-L50) is defined as empty function macro, static assert is disabled.

```
#define PMACC_STATIC_ASSERT_MSG_DO2( ... )
```

**Comment by ax3l** [comment]
solution would be too intrusive.
we decide to recommend: C++98 <= CUDA 7.0 and C++11 >= CUDA 7.5
