### PR TITLE
Fix complex math abs and abs2 issues

### LINKED ISSUE #3379: Complex math is partially broken
#3245 introduced at least two bugs in complex math implementation, that originally went unnoticed:
- `abs()` implementation is wrong
- return types of `abs()` and `abs2()` got changed from real to complex, but the remaining implementations, like `pow()`, `log()`, `exp()` seems to assume it's real which results in at least unnecessary recursion and may be an infinite one as well. So will need to go back to real.

We just discussed it offline with @psychocoderHPC and @BeyondEspresso . Please feel free to add if I missed some other malfunctions in the description.

Luckily, this change was made after 0.5.0 release and so does **not** affect it.

### PR DESCRIPTION
**Pull request by sbastrakov**
The issues were introduced in #3245 and went unnoriced until #3379 .

Fix wrong formula in `Abs` implementation.
Make return types of `Abs` and `Abs2` real, as they were before that change.

Fixes #3379 .

### CODE REVIEW

**Review by psychocoderHPC — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
@BeyondEspresso PLease check if this solves you issues

**Comment by BeyondEspresso** [comment]
For documentation, the PR created following compile error
```
/home/debus/src/picongpu/thirdParty/cupla/alpaka/include/alpaka/math/sqrt/Traits.hpp(51): error #70: incomplete type is not allowed
          detected during:
            instantiation of "auto alpaka::math::sqrt(const T &, const TArg &) [with T=alpaka::math::AbsUniformCudaHipBuiltIn, TArg=picongpu::float_X]" 
/home/debus/src/picongpu/include/pmacc/../pmacc/math/complex/Complex.tpp(224): here
            instantiation of "auto alpaka::math::traits::Abs<T_Ctx, pmacc::math::Complex<T_Type>, void>::abs(const T_Ctx &, const pmacc::math::Complex<T_Type> &)->T_Type [with T_Ctx=alpaka::math::AbsUniformCudaHipBuiltIn, T_Type=picongpu::float_X]" 
/home/debus/src/picongpu/thirdParty/cupla/include/cupla/device/math/Abs.hpp(37): here
            instantiation of "auto cupla::cupla_cuda_async::device::math::abs(const T_Type &)->decltype((<expression>)) [with T_Type=pmacc::math::Complex<picongpu::float_X>]" 
/home/debus/src/picongpu/include/pmacc/../pmacc/math/complex/Complex.tpp(182): here
            instantiation of "auto alpaka::math::traits::Sqrt<T_Ctx, pmacc::math::Complex<T_Type>, void>::sqrt(const T_Ctx &, const pmacc::math::Complex<T_Type> &)->pmacc::math::Complex<T_Type> [with T_Ctx=alpaka::math::SqrtUniformCudaHipBuiltIn, T_Type=picongpu::float_X]" 
/home/debus/src/picongpu/thirdParty/cupla/include/cupla/device/math/Root.hpp(37): here
            instantiation of "auto cupla::cupla_cuda_async::device::math::sqrt(const T_Type &)->decltype((<expression>)) [with T_Type=pmacc::math::Complex<picongpu::float_X>]" 
/home/debus/src/picongpu/include/pmacc/../picongpu/fields/background/templates/TWTS/EField.tpp(334): here

```

**Comment by sbastrakov** [comment]
So I made a mistake in the fixed Abs implementation. Not sure what is it from the first look, will investigate tomorrow morning. Thanks for testing @BeyondEspresso , sorry it did not work as i imagined it would.

**Comment by sbastrakov** [comment]
@BeyondEspresso there was a tricky error in my original implementation. It is hopefully fixed (at least my small test compiled, but of course you have a more complex use case) now with the current state of this branch

**Comment by BeyondEspresso** [comment]
@sbastrakov I ran my test case with your new branch and the results are virtually the same:
TWTSTest1
TWTSTest2

**Review by psychocoderHPC — APPROVED** [review]
